server:
  port: 7777

spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: o7qp8d.E4eFx:b^06isu
  jackson:
    serialization:
      indent_output: true

logging:
  level:
    root: INFO
    org:
      springframework:
        security: TRACE
        web: TRACE
      hibernate: INFO
      apache:
        commons:
          dbcp2: DEBUG

